# Generated by Django 4.2.7 on 2023-12-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="feactured",
            new_name="featured",
        ),
    ]
